mod config; mod platform; mod security;
use axum::{extract::State,response::Html,routing::get,Json,Router};
use clap::{Parser,ValueEnum}; use platform::*; use security::{is_root,CommandPolicy}; use serde::{Deserialize,Serialize};
use std::{collections::{HashMap,VecDeque},net::SocketAddr,path::PathBuf,sync::{Arc,Mutex,atomic::{AtomicU32,Ordering}},time::{Duration,Instant}};
use sysinfo::{Components,CpuRefreshKind,RefreshKind,System}; use tokio::io::{AsyncBufReadExt,BufReader}; use tokio_stream::wrappers::ReceiverStream;
use tonic::{transport::Server,Request,Response,Status}; use tower_http::cors::CorsLayer; use tracing::{error,info,warn}; use uuid::Uuid;
pub mod aether_grpc{tonic::include_proto!("aether");}
use aether_grpc::{HeartbeatRequest,HeartbeatResponse,TaskRequest,TaskResponse};
use aether_grpc::master_service_client::MasterServiceClient; use aether_grpc::master_service_server::{MasterService,MasterServiceServer};
use aether_grpc::worker_service_client::WorkerServiceClient; use aether_grpc::worker_service_server::{WorkerService,WorkerServiceServer};
#[derive(Debug,Clone,Copy,PartialEq,Eq,ValueEnum)] enum Mode{Master,Worker,Client}
#[derive(Parser,Debug)] #[command(name="aether",author="CFSJCODE",version="0.2.0")]
struct Args{#[arg(short,long,value_enum)]mode:Mode,#[arg(short,long,default_value_t=50051)]port:u16,#[arg(short='i',long,default_value="127.0.0.1")]master_ip:String,#[arg(short='c',long,default_value="")]command:String,#[arg(long)]worker_id:Option<String>,#[arg(long)]worker_port:Option<u16>,#[arg(long,default_value_t=2)]max_concurrent_tasks:u32,#[arg(long,default_value_t=8080)]web_port:u16,#[arg(long,default_value_t=true,action=clap::ArgAction::Set)]enable_web:bool,#[arg(long,default_value_t=250)]scheduler_interval_ms:u64,#[arg(long,default_value_t=6)]heartbeat_timeout_seconds:u64,#[arg(long,default_value_t=false)]allow_unsafe_commands:bool,#[arg(long,default_value_t=false)]allow_root:bool,#[arg(long,value_delimiter=',',default_value="")]tags:Vec<String>,#[arg(long,value_delimiter=',')]allowed_command:Vec<String>,#[arg(long)]config:Option<PathBuf>,#[arg(long,default_value_t=false)]enable_process_thief:bool}
#[derive(Clone)] struct W{ip:String,port:u32,last:Instant,cpu:f32,ram:f32,tmp:f32,run:u32,max:u32,os:String,sh:String,tags:Vec<String>} impl W{fn score(&self)->f32{let c=(100.0-self.cpu).clamp(0.0,100.0);let r=(100.0-self.ram).clamp(0.0,100.0);let th=if self.tmp<=0.0{85.0}else if self.tmp>82.0{0.0}else if self.tmp>70.0{(100.0-(self.tmp-70.0)*5.0).clamp(0.0,100.0)}else{100.0};let sl=if self.max==0{0.0}else{(self.max.saturating_sub(self.run)as f32/self.max as f32*100.0).clamp(0.0,100.0)};c*0.35+r*0.20+th*0.25+sl*0.20}fn tags(&self,r:&[String])->bool{r.iter().all(|x|self.tags.iter().any(|y|y.eq_ignore_ascii_case(x)))}}
#[derive(Clone)] struct T{id:String,cmd:String,tags:Vec<String>,timeout:u32,prio:i32}
#[derive(Clone,Serialize)] struct TV{id:String,command:String,status:String,worker:Option<String>,stdout_tail:String,stderr_tail:String}
#[derive(Clone)] struct M{workers:Arc<Mutex<HashMap<String,W>>>,q:Arc<Mutex<VecDeque<T>>>,hist:Arc<Mutex<Vec<TV>>>,pol:CommandPolicy} impl M{fn new(pol:CommandPolicy)->Self{Self{workers:Arc::default(),q:Arc::default(),hist:Arc::default(),pol}}fn push(&self,t:T){self.hist.lock().unwrap().push(TV{id:t.id.clone(),command:t.cmd.clone(),status:"QUEUED".into(),worker:None,stdout_tail:String::new(),stderr_tail:String::new()});self.q.lock().unwrap().push_back(t)}fn upd(&self,id:&str,st:&str,w:Option<String>,o:&str,e:&str){let mut h=self.hist.lock().unwrap();if let Some(x)=h.iter_mut().find(|x|x.id==id){x.status=st.into();if w.is_some(){x.worker=w}x.stdout_tail=tail(o);x.stderr_tail=tail(e)}if h.len()>500{h.drain(0..100);}}}
#[tonic::async_trait] impl MasterService for M{async fn send_heartbeat(&self,req:Request<HeartbeatRequest>)->Result<Response<HeartbeatResponse>,Status>{let ip=req.remote_addr().map(|a|if a.ip().to_string()=="::1"{"127.0.0.1".into()}else{a.ip().to_string()}).unwrap_or("127.0.0.1".into());let r=req.into_inner();let id=r.worker_id.clone();let w=W{ip,port:r.worker_port.max(50052),last:Instant::now(),cpu:r.cpu_usage,ram:r.ram_usage,tmp:r.temperature,run:r.running_tasks,max:r.max_concurrent_tasks.max(1),os:r.operating_system,sh:r.shell,tags:r.tags};let new=self.workers.lock().unwrap().insert(id.clone(),w).is_none();info!(worker_id=%id,"heartbeat");if new{self.push(T{id:"task_01_sysinfo".into(),cmd:"hostname".into(),tags:vec![],timeout:30,prio:5})}Ok(Response::new(HeartbeatResponse{acknowledged:true}))}async fn inject_task(&self,req:Request<TaskRequest>)->Result<Response<TaskResponse>,Status>{let r=req.into_inner();self.pol.validate(&r.command).map_err(|e|Status::permission_denied(e.to_string()))?;let id=if r.task_id.is_empty(){format!("client_{}",Uuid::new_v4())}else{format!("client_{}",r.task_id)};self.push(T{id:id.clone(),cmd:r.command,tags:r.required_tags,timeout:r.timeout_seconds.max(30),prio:r.priority});Ok(Response::new(TaskResponse{task_id:id,exit_code:0,stdout:"Tarefa enfileirada no Master.\n".into(),stderr:String::new()}))}}
#[derive(Clone)] struct WR{pol:CommandPolicy,run:Arc<AtomicU32>,max:u32} impl WR{fn new(pol:CommandPolicy,max:u32)->Self{Self{pol,run:Arc::new(AtomicU32::new(0)),max:max.max(1)}}}
#[tonic::async_trait] impl WorkerService for WR{type ExecuteTaskStream=ReceiverStream<Result<TaskResponse,Status>>;async fn execute_task(&self,req:Request<TaskRequest>)->Result<Response<Self::ExecuteTaskStream>,Status>{let r=req.into_inner();self.pol.validate(&r.command).map_err(|e|Status::permission_denied(e.to_string()))?;if self.run.fetch_add(1,Ordering::SeqCst)>=self.max{self.run.fetch_sub(1,Ordering::SeqCst);return Err(Status::resource_exhausted("Worker sem slots livres"))}let(id,run,timeout)=(r.task_id.clone(),self.run.clone(),r.timeout_seconds.max(30));let(tx,rx)=tokio::sync::mpsc::channel(64);let mut c=build_shell_command(&r.command);let mut child=configure_process_stdio(&mut c).spawn().map_err(|e|{self.run.fetch_sub(1,Ordering::SeqCst);Status::internal(e.to_string())})?;if let Some(o)=child.stdout.take(){pipe(o,tx.clone(),id.clone(),false)}if let Some(e)=child.stderr.take(){pipe(e,tx.clone(),id.clone(),true)}tokio::spawn(async move{let s=tokio::time::timeout(Duration::from_secs(timeout as u64),child.wait()).await;run.fetch_sub(1,Ordering::SeqCst);let(code,out,err)=match s{Ok(Ok(x))=>(x.code().unwrap_or(0),"[WORKER] --- Micro-lote finalizado ---\n".into(),String::new()),Ok(Err(e))=>(-1,String::new(),format!("{e}\n")),Err(_)=>(-1,String::new(),"timeout\n".into())};let _=tx.send(Ok(TaskResponse{task_id:id,exit_code:code,stdout:out,stderr:err})).await;});Ok(Response::new(ReceiverStream::new(rx)))}}
fn pipe<R:tokio::io::AsyncRead+Unpin+Send+'static>(p:R,tx:tokio::sync::mpsc::Sender<Result<TaskResponse,Status>>,id:String,err:bool){tokio::spawn(async move{let mut l=BufReader::new(p).lines();while let Ok(Some(x))=l.next_line().await{let m=if err{TaskResponse{task_id:id.clone(),exit_code:0,stdout:String::new(),stderr:format!("{x}\n")}}else{TaskResponse{task_id:id.clone(),exit_code:0,stdout:format!("{x}\n"),stderr:String::new()}};let _=tx.send(Ok(m)).await;}});}
#[tokio::main] async fn main()->anyhow::Result<()>{tracing_subscriber::fmt().with_env_filter(tracing_subscriber::EnvFilter::new("aether=info,tower_http=warn")).init();let a=Args::parse();let cfg=config::load_config(a.config.as_deref())?;let mut p=CommandPolicy::default();if let Some(s)=cfg.security{if let Some(v)=s.allow_unsafe_commands{p.allow_unsafe_commands=v}if let Some(v)=s.allowed_commands{p.allowed_prefixes=v}}if a.allow_unsafe_commands{p.allow_unsafe_commands=true}if !a.allowed_command.is_empty(){p.allowed_prefixes=a.allowed_command.clone()}if a.enable_process_thief{warn!("Process Thief desativado por segurança")};match a.mode{Mode::Master=>master(a,p).await,Mode::Worker=>worker(a,p).await,Mode::Client=>client(a).await}}
async fn master(a:Args,p:CommandPolicy)->anyhow::Result<()>{let m=M::new(p);reaper(m.clone(),a.heartbeat_timeout_seconds);sched(m.clone(),a.scheduler_interval_ms);if a.enable_web{let x=m.clone();let ad=format!("0.0.0.0:{}",a.web_port).parse()?;tokio::spawn(async move{if let Err(e)=web(x,ad).await{error!(%e,"Aether Console falhou")}});}let ad=format!("0.0.0.0:{}",a.port).parse()?;Server::builder().add_service(MasterServiceServer::new(m)).serve(ad).await?;Ok(())}
async fn worker(a:Args,p:CommandPolicy)->anyhow::Result<()>{if is_root()&&!a.allow_root{anyhow::bail!("recusando execução do Worker como root")};let port=a.worker_port.unwrap_or(a.port+1);let id=resolve_worker_id(a.worker_id.clone());let tags=norm(a.tags,&id);let w=WR::new(p,a.max_concurrent_tasks);let hb=w.clone();let ad=format!("0.0.0.0:{port}").parse()?;tokio::spawn(async move{if let Err(e)=Server::builder().add_service(WorkerServiceServer::new(w)).serve(ad).await{error!(%e,"Worker falhou")}});let mut c=MasterServiceClient::connect(format!("http://{}:{}",a.master_ip,a.port)).await?;let mut sys=System::new_with_specifics(RefreshKind::new().with_cpu(CpuRefreshKind::everything()));loop{sys.refresh_cpu_usage();sys.refresh_memory();let ram=if sys.total_memory()==0{0.0}else{sys.used_memory()as f32/sys.total_memory()as f32*100.0};let cpu=sys.global_cpu_info().cpu_usage();let req=Request::new(HeartbeatRequest{worker_id:id.clone(),cpu_usage:cpu,ram_usage:ram,temperature:temp(),worker_port:port as u32,operating_system:operating_system().into(),running_tasks:hb.run.load(Ordering::Relaxed),max_concurrent_tasks:a.max_concurrent_tasks.max(1),load_average:cpu,tags:tags.clone(),shell:ShellKind::current().as_str().into()});if let Err(e)=c.send_heartbeat(req).await{warn!(%e,"heartbeat falhou")};tokio::time::sleep(Duration::from_secs(2)).await}}
async fn client(a:Args)->anyhow::Result<()>{if a.command.is_empty(){anyhow::bail!("forneça --command/-c")};let mut c=MasterServiceClient::connect(format!("http://{}:{}",a.master_ip,a.port)).await?;let r=c.inject_task(Request::new(TaskRequest{task_id:"manual_cli".into(),command:a.command,payload:vec![],timeout_seconds:30,required_tags:norm(a.tags,"client"),priority:5})).await?;println!("{}",r.into_inner().stdout.trim());Ok(())}
fn reaper(m:M,t:u64){tokio::spawn(async move{loop{tokio::time::sleep(Duration::from_secs(5)).await;let now=Instant::now();m.workers.lock().unwrap().retain(|id,w|{let ok=now.duration_since(w.last).as_secs()<=t;if !ok{warn!(worker_id=%id,"Worker expirado")};ok});}});}fn sched(m:M,ms:u64){tokio::spawn(async move{loop{tokio::time::sleep(Duration::from_millis(ms.max(50))).await;let Some(t)=m.q.lock().unwrap().pop_front()else{continue};let Some((id,ip,port))=choose(&m,&t.tags)else{m.q.lock().unwrap().push_front(t);continue};m.upd(&t.id,"DISPATCHED",Some(id.clone()),"","");let mm=m.clone();tokio::spawn(async move{match WorkerServiceClient::connect(format!("http://{ip}:{port}")).await{Ok(mut c)=>match c.execute_task(Request::new(TaskRequest{task_id:t.id.clone(),command:t.cmd.clone(),payload:vec![],timeout_seconds:t.timeout,required_tags:t.tags.clone(),priority:t.prio})).await{Ok(r)=>{let mut s=r.into_inner();let(mut o,mut e,mut code)=(String::new(),String::new(),0);while let Ok(Some(x))=s.message().await{o.push_str(&x.stdout);e.push_str(&x.stderr);code=x.exit_code}mm.upd(&t.id,if code==0{"SUCCEEDED"}else{"FAILED"},Some(id),&o,&e)},Err(e)=>{mm.upd(&t.id,"RETRYING",Some(id),"",&e.to_string());mm.q.lock().unwrap().push_back(t)}},Err(e)=>{warn!(%e,"conexão com Worker falhou");mm.q.lock().unwrap().push_back(t)}}});}});}fn choose(m:&M,req:&[String])->Option<(String,String,u32)>{let mut b=None;let mut w=m.workers.lock().unwrap();for(id,x)in w.iter_mut(){let s=x.score();if s>30.0&&x.run<x.max&&x.tags(req)&&b.as_ref().map(|(_,_,_,bs)|s>*bs).unwrap_or(true){b=Some((id.clone(),x.ip.clone(),x.port,s))}}if let Some((id,_,_,_))=&b{if let Some(x)=w.get_mut(id){x.run=x.run.saturating_add(1)}}b.map(|(a,b,c,_)|(a,b,c))}
async fn web(m:M,ad:SocketAddr)->anyhow::Result<()>{let app=Router::new().route("/",get(||async{Html(INDEX)})).route("/api/cluster/status",get(status)).route("/api/workers",get(workers)).route("/api/tasks",get(tasks).post(task)).layer(CorsLayer::permissive()).with_state(m);let l=tokio::net::TcpListener::bind(ad).await?;axum::serve(l,app).await?;Ok(())}async fn status(State(m):State<M>)->Json<serde_json::Value>{Json(serde_json::json!({"workers_online":m.workers.lock().unwrap().len(),"tasks_queued":m.q.lock().unwrap().len(),"tasks_tracked":m.hist.lock().unwrap().len()}))}#[derive(Serialize)]struct WV{id:String,ip:String,port:u32,cpu:f32,ram:f32,temp:f32,running:u32,max:u32,os:String,shell:String,tags:Vec<String>,score:f32}async fn workers(State(m):State<M>)->Json<Vec<WV>>{Json(m.workers.lock().unwrap().iter().map(|(id,w)|WV{id:id.clone(),ip:w.ip.clone(),port:w.port,cpu:w.cpu,ram:w.ram,temp:w.tmp,running:w.run,max:w.max,os:w.os.clone(),shell:w.sh.clone(),tags:w.tags.clone(),score:w.score()}).collect())}async fn tasks(State(m):State<M>)->Json<Vec<TV>>{Json(m.hist.lock().unwrap().clone())}#[derive(Deserialize)]struct WT{command:String,required_tags:Option<Vec<String>>,timeout_seconds:Option<u32>,priority:Option<i32>}async fn task(State(m):State<M>,Json(t):Json<WT>)->Result<Json<serde_json::Value>,(axum::http::StatusCode,String)>{m.pol.validate(&t.command).map_err(|e|(axum::http::StatusCode::FORBIDDEN,e.to_string()))?;let id=format!("web_{}",Uuid::new_v4());m.push(T{id:id.clone(),cmd:t.command,tags:t.required_tags.unwrap_or_default(),timeout:t.timeout_seconds.unwrap_or(30),prio:t.priority.unwrap_or(5)});Ok(Json(serde_json::json!({"task_id":id})))}
fn norm(v:Vec<String>,id:&str)->Vec<String>{let mut x:Vec<_>=v.into_iter().map(|s|s.trim().to_lowercase()).filter(|s|!s.is_empty()).collect();x.push(operating_system().into());x.push(ShellKind::current().as_str().into());if id.contains("local"){x.push("local".into())}x.sort();x.dedup();x}fn temp()->f32{for c in &Components::new_with_refreshed_list(){let l=c.label().to_lowercase();if l.contains("cpu")||l.contains("core")||l.contains("tctl")||l.contains("tdie"){return c.temperature()}}0.0}fn tail(s:&str)->String{s.chars().rev().take(4096).collect::<Vec<_>>().into_iter().rev().collect()}
const INDEX:&str="<!doctype html><meta charset=utf-8><title>Aether Console</title><body style='font-family:Segoe UI;background:#0b1020;color:#e5e7eb'><h1>Aether Console</h1><textarea id=cmd>hostname</textarea><button onclick=send()>Enfileirar</button><pre id=o></pre><script>async function j(u,o){let r=await fetch(u,o);return r.json()}async function ref(){o.textContent=JSON.stringify({status:await j('/api/cluster/status'),workers:await j('/api/workers'),tasks:await j('/api/tasks')},null,2)}async function send(){await j('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:cmd.value})});ref()}ref();setInterval(ref,2500)</script>";
